
name: Outpost
version: 1.3.1
main: dev.elliot.outpost.OutpostPlugin
api-version: '1.21'

commands:
  setoutpost:
    permission: outpost.admin
  stopoutpost:
    permission: outpost.admin

permissions:
  outpost.admin:
    default: op
