name: Outpost
version: 1.3.3
main: dev.elliot.outpost.OutpostPlugin
api-version: '1.21'
commands:
  setoutpost:
    permission: outpost.admin
  stopoutpost:
    permission: outpost.admin
  rewards:
    permission: outpost.use
  reward:
    permission: outpost.admin