
name: Outpost
version: 1.0.0
main: dev.elliot.outpost.OutpostPlugin
api-version: '1.21'
author: Elliot
description: Capture the Outpost plugin

commands:
  setoutpost:
    description: Create an outpost
    usage: /setoutpost <time> <radius> <height>
    permission: outpost.admin

permissions:
  outpost.admin:
    default: op
